# coding=utf-8
# -*- coding: UTF-8 -*-
# -*- coding: UTF-8 -*-
import sys, os, re

string_padding = "pad"
float_padding = 0.0
feature_id_padding = -1
placeholder_str = "<ph>"
config_realtime = {
    "label": {
        "name": "label",
        "type": "label",
        "field_size": 1,
        "using": 1,
        "value_type": "dense",
        "feature_index": 17,
        "shared_field": "",
    },
    "item_freq": {
        "name": "item_freq",
        "type": "label",
        "field_size": 1,
        "using": 1,
        "value_type": "dense",
        "feature_index": 27,
        "shared_field": "",
    },
    "watch_time": {
        "name": "watch_time",
        "type": "label",
        "field_size": 1,
        "using": 1,
        "value_type": "dense",
        "feature_index": 53,
        "shared_field": "",
    },
    "vtime": {
        "name": "vtime",
        "type": "label",
        "field_size": 1,
        "using": 1,
        "value_type": "dense",
        "feature_index": 90,
        "shared_field": "",
    },
    "user_age": {
        "name": "user_age",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 4,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 19,
    },
    "user_category1": {
        "name": "user_category1",
        "hash_size": 100001,
        "shared_field": "",
        "type": "user",
        "emb_size": 8,
        "field_size": 5,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 21,
        "is_weight": "false",
        "embedding_weight": "user_category1_score",
    },
    "user_category1_score": {
        "name": "user_category1_score",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 12,
        "field_size": 5,
        "attention_heads": 0,
        "using": 0,
        "value_type": "dense",
        "feature_index": 21,
        "is_weight": "true",
        "embedding_weight": "",
        "split_index": 1,
    },
    "user_category2": {
        "name": "user_category2",
        "hash_size": 100001,
        "shared_field": "",
        "type": "user",
        "emb_size": 8,
        "field_size": 5,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 22,
        "is_weight": "false",
        "embedding_weight": "user_category2_score",
    },
    "user_category2_score": {
        "name": "user_category2_score",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 12,
        "field_size": 5,
        "attention_heads": 0,
        "using": 0,
        "value_type": "dense",
        "feature_index": 22,
        "is_weight": "true",
        "embedding_weight": "",
        "split_index": 1,
    },
    "user_city": {
        "name": "user_city",
        "hash_size": 100001,
        "shared_field": "",
        "type": "user",
        "emb_size": 8,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 20,
    },
    "user_flush_num": {
        "name": "user_flush_num",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 4,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 60,
    },
    "user_realtime_pos_video": {
        "name": "user_realtime_pos_video",
        "hash_size": 10000001,
        "shared_field": "shared_newsid",
        "type": "user",
        "emb_size": 12,
        "field_size": 50,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 137,
    },
    "user_history": {
        "name": "user_history",
        "hash_size": 10000001,
        "shared_field": "shared_newsid",
        "type": "user",
        "emb_size": 12,
        "field_size": 25,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 65,
    },
    "user_id": {
        "name": "user_id",
        "hash_size": 100000001,
        "shared_field": "",
        "type": "user",
        "emb_size": 8,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 2,
    },
    "user_sex": {
        "name": "user_sex",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 4,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 18,
    },
    "user_tag_terms": {
        "name": "user_tag_terms",
        "hash_size": 1000001,
        "shared_field": "",
        "type": "user",
        "emb_size": 8,
        "field_size": 20,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 23,
        "is_weight": "false",
        "embedding_weight": "user_tag_terms_score",
    },
    "user_tag_terms_score": {
        "name": "user_tag_terms_score",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 12,
        "field_size": 20,
        "attention_heads": 0,
        "using": 0,
        "value_type": "dense",
        "feature_index": 23,
        "is_weight": "true",
        "embedding_weight": "",
        "split_index": 1,
    },
    "user_top_newscat1": {
        "name": "user_top_newscat1",
        "hash_size": 100001,
        "shared_field": "shared_video_cat1",
        "type": "user",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 81,
    },
    "user_top_newscat2": {
        "name": "user_top_newscat2",
        "hash_size": 100001,
        "shared_field": "shared_video_cat2",
        "type": "user",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 82,
    },
    "user_top_newsid": {
        "name": "user_top_newsid",
        "hash_size": 10000001,
        "shared_field": "shared_newsid",
        "type": "user",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 80,
    },
    "user_top_newstags": {
        "name": "user_top_newstags",
        "hash_size": 1000001,
        "shared_field": "shared_video_tagterm",
        "type": "user",
        "emb_size": 12,
        "field_size": 8,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 83,
    },
    "user_video_category1": {
        "name": "user_video_category1",
        "hash_size": 100001,
        "shared_field": "shared_video_cat1",
        "type": "user",
        "emb_size": 8,
        "field_size": 5,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 61,
        "is_weight": "false",
        "embedding_weight": "user_video_category1_score",
    },
    "user_video_category1_score": {
        "name": "user_video_category1_score",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 12,
        "field_size": 5,
        "attention_heads": 0,
        "using": 0,
        "value_type": "dense",
        "feature_index": 61,
        "is_weight": "true",
        "embedding_weight": "",
        "split_index": 1,
    },
    "user_video_category2": {
        "name": "user_video_category2",
        "hash_size": 100001,
        "shared_field": "shared_video_cat2",
        "type": "user",
        "emb_size": 8,
        "field_size": 5,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 62,
        "is_weight": "false",
        "embedding_weight": "user_video_category2_score",
    },
    "user_video_category2_score": {
        "name": "user_video_category2_score",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 12,
        "field_size": 5,
        "attention_heads": 0,
        "using": 0,
        "value_type": "dense",
        "feature_index": 62,
        "is_weight": "true",
        "embedding_weight": "",
        "split_index": 1,
    },
    "user_video_tag": {
        "name": "user_video_tag",
        "hash_size": 1000001,
        "shared_field": "shared_video_tagterm",
        "type": "user",
        "emb_size": 8,
        "field_size": 20,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 63,
        "is_weight": "false",
        "embedding_weight": "user_video_tag_score",
    },
    "user_video_tag_score": {
        "name": "user_video_tag_score",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 12,
        "field_size": 20,
        "attention_heads": 0,
        "using": 0,
        "value_type": "dense",
        "feature_index": 63,
        "is_weight": "true",
        "embedding_weight": "",
        "split_index": 1,
    },
    "user_visit_time": {
        "name": "user_visit_time",
        "hash_size": 1001,
        "shared_field": "",
        "type": "user",
        "emb_size": 2,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 4,
    },
    "user_PAGE_START": {
        "name": "user_PAGE_START",
        "hash_size": 11,
        "shared_field": "",
        "type": "user",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 135,
    },
    "item_contentlevel": {
        "name": "item_contentlevel",
        "hash_size": 1001,
        "shared_field": "",
        "type": "item",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 93,
        "index_name": "vcl",
    },
    "item_pt_time": {  # item_news_hour
        "name": "item_pt_time",
        "hash_size": 1001,
        "shared_field": "",
        "type": "item",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "dense",
        "feature_index": 9,
        "index_name": "pt",
    },
    "item_coverpicscore": {
        "name": "item_coverpicscore",
        "hash_size": 1001,
        "shared_field": "",
        "type": "item",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 97,
        "index_name": "cps",
    },
    "item_isgoodcontent": {
        "name": "item_isgoodcontent",
        "hash_size": 1001,
        "shared_field": "",
        "type": "item",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 92,
        "index_name": "vgc",
    },
    "item_news_category1": {
        "name": "item_news_category1",
        "hash_size": 100001,
        "shared_field": "shared_video_cat1",
        "type": "item",
        "emb_size": 8,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 13,
        "index_name": "category1_id_to_map",  # need to split
    },
    "item_news_category2": {
        "name": "item_news_category2",
        "hash_size": 100001,
        "shared_field": "shared_video_cat2",
        "type": "item",
        "emb_size": 8,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 14,
        "index_name": "category2_id_to_map",  # need to split
    },
    "item_news_media": {
        "name": "item_news_media",
        "hash_size": 100001,
        "shared_field": "",
        "type": "item",
        "emb_size": 8,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 7,
        "index_name": "src",
    },
    "item_news_mediascore": {
        "name": "item_news_mediascore",
        "hash_size": 1001,
        "shared_field": "",
        "type": "item",
        "emb_size": 4,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 12,
        "index_name": "mrank",
    },
    "item_news_score": {
        "name": "item_news_score",
        "hash_size": 1001,
        "shared_field": "",
        "type": "item",
        "emb_size": 4,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 11,
        "index_name": "nrank",  # 似乎没有这个字段
    },
    "item_news_tagterms": {
        "name": "item_news_tagterms",
        "hash_size": 1000001,
        "shared_field": "shared_video_tagterm",
        "type": "item",
        "emb_size": 8,
        "field_size": 8,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 16,
        "index_name": "ntag_id_to_map",
    },
    "item_newsid": {
        "name": "item_newsid",
        "hash_size": 10000001,
        "shared_field": "shared_newsid",
        "type": "item",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 1,
        "index_name": "id",
    },
    "item_piclevel": {
        "name": "item_piclevel",
        "hash_size": 1001,
        "shared_field": "",
        "type": "item",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 96,
        "index_name": "vps",
    },
    "item_picresolution": {
        "name": "item_picresolution",
        "hash_size": 100001,
        "shared_field": "",
        "type": "item",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 0,
        "value_type": "string",
        "feature_index": 95,
        "index_name": "vpr",
    },
    "item_titlescale": {
        "name": "item_titlescale",
        "hash_size": 1001,
        "shared_field": "",
        "type": "item",
        "emb_size": 12,
        "field_size": 1,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 94,
        "index_name": "vts",
    },
    "item_concept_tags": {
        "name": "item_concept_tags",
        "hash_size": 1000001,
        "shared_field": "",
        "type": "item",
        "emb_size": 12,
        "field_size": 5,
        "attention_heads": 0,
        "using": 1,
        "value_type": "string",
        "feature_index": 146,
        "index_name": "video_concept_tag_id_to_map",
    },
}


def format_features(
    input_fea_str, fea_len, split_index, default_val=feature_id_padding
):
    out_list = [default_val] * fea_len
    for i, _id in enumerate(input_fea_str.split(",")):
        if _id:
            _id = _id.split(":")[split_index]
            if i >= fea_len:
                break
            out_list[i] = int(_id)

    return out_list


def format_string(input_fea_str, fea_len, split_index, default_val=string_padding):
    out_list = [default_val] * fea_len
    for i, _id in enumerate(input_fea_str.split(",")):
        if _id:
            _id = _id.split(":")[split_index]
            if i >= fea_len:
                break
            if (
                len(_id) == 16 and len(re.findall(r"[0-9]{8}.*0[0-1]", _id)) > 0
            ):  # find newsid 20210324V0955W00 to 20210324V0955W
                _id = _id[:-2]
            out_list[i] = _id
    return out_list


def format_float(input_fea_str, fea_len, split_index, default_val=float_padding):
    out_list = [default_val] * fea_len
    for i, _id in enumerate(input_fea_str.split(",")):
        if _id:
            _id = _id.split(":")[split_index]
            if i >= fea_len:
                break
            out_list[i] = float(_id)
    return out_list
